#######################################################################
# This file is automatically generated from System Generator for DSP  #
# design. Consult the documentation before making any modifications   #
#######################################################################
set rateCe2 default_clock_driver/xlclockdriver_2/pipelined_ce.ce_pipeline[1].ce_reg/latency_gt_0.fd_array[1].reg_comp/fd_prim_array[0].bit_is_0.fdre_comp
set rateCells2 [get_cells -of [filter [all_fanout -flat -endpoints [get_pins $rateCe2/Q]] IS_ENABLE]]
set_multicycle_path -from $rateCells2 -to $rateCells2 -setup 2
set_multicycle_path -from $rateCells2 -to $rateCells2 -hold 1


