#######################################################################
# This file is automatically generated from System Generator for DSP  #
# design. Consult the documentation before making any modifications   #
#######################################################################
# Global Clock Constraints
create_clock -name clk -period 10.000 [get_ports clk]
